### PR TITLE
Restructuring DX

### PR DESCRIPTION
**Pull request by iamhectorsosa**
Working with the `/components` route:

1. Create or use an existing MailingUI component primitive from `@mailingui/components`
2. Create an example of how to use it in `src/examples/components` and make sure to enable your component using default exports. 

No need for any special file conventions as long as it is placed in folder (i.e. `src/examples/components/badges`) that matches a registered type.

```tsx
// @path `src/examples/components/badges/LargeBadges.tsx`
/** Importing a MailingUI component primitive */
import { Badge } from "@mailingui/components";

export default function LargeBadges(){ ... };
```

- A component primitive can be used in one or multiple examples.
- You can also import themes from `import { Heading, theme } from "@mailingui/components";`
- Templates will be extended with the same structure, you can import a template from `import { Badge, theme } from "@mailingui/bianco/components";` A mapping has been enabled in the project's `tsconfig.json`.

From the preview build, check the examples created for `/components/badges`

image

## Next Steps

I'm thinking of adding a markdown file in each folder where we can add the documentation part (i.e. `src/examples/components/badges/usage.mdx`? It would also be picked up by reading the `fs` like everything else. That way we can describe installation and other relevant information. Of course, all of this is open for discussion.

### CODE REVIEW

**Comment by iamhectorsosa** [comment]
Here it goes, let me know what you guys think @jvorcak @ericvalcik

**Comment by ericvalcik** [comment]
I like this very much. I think the structure is perfect and we are not compromising any DX, tbh, I would say that the DX is even better 😄.

About the **Next Steps** section. I also think adding some description/documentation at the top of each Component's examples would be nice. I also really liked the option for the _manual install_, meaning at the top there would be by default closed tab with the source code of the primitive, that is being imported below. Users not wanting to install our package could copy the source code.

Although another thought about this idea, we would strictly have to only depend on `react` and `@react-email` for components, nothing else, right? Is that a good approach?

**Review by ericvalcik — APPROVED** [review]

**Comment by iamhectorsosa** [comment]
Great suggestions, @ericvalcik. We need to think more about this and iterate to see what fits our project best. For now, I think that if there are no major concerns with this structure, we can more forward with component development.

**Comment by jvorcak** [comment]
GJ @iamhectorsosa , I agree with @ericvalcik. Otherwise good job!

**Review by jvorcak — APPROVED** [review]

**Pull request merged**
