### PR TITLE
Paragraph component

### PR DESCRIPTION
**Pull request by ericvalcik**
With this PR, new component `<Paragraph>` is introduced along with 3 examples.

### CODE REVIEW

**Review by iamhectorsosa — CHANGES_REQUESTED** [review]
Great addition to the library but still space for improvement. Here is what I think it would be good to think about adding:

- Consuming theme for font family
- Consuming theme for color
- Font size props for small, base, large
- Line height props for normal, relaxed and loose

Then on the examples I would be great to see paragraphs in these cases
- Paragraphs standard
- Paragraph centered
- Paragraph consuming different theme (use one example for anything coming from theme)
- Paragraphs with relaxed
- Paragraphs with loose
- Paragraph with different font size props, easiest example would be Thank you message to showcase the large text and then immediately after a small text with a disclaimer. This would be a nice use case.

Get inspo from the Typography category in TailwindCSS. We're almost there on this one.

**Comment by ericvalcik** [comment]
All the comments Hector made are implemented, except for the `line-height` suggestion. I added a `size` prop that automatically sets both `font-size` and `line-height`, so they are tied together - however this can be overridden with the `style` prop.

IMO this is the more user-friendly solution, as I feel like the `line-height` is tied to the `font-size` and I can imagine that most of the time I'm just changing the size as a whole not the `font-size` or `line-height` individually.

With this, I also omitted the Example with line height and sizes and just included it into one Example. I also added another example (the `Custom Styled Paragraphs`) to fully show how our Paragraphs can be used.

Tell me what you think @iamhectorsosa.

**Review by iamhectorsosa — APPROVED** [review]
Looking real good!

**Review by iamhectorsosa — COMMENTED** [review]
An additional request: Could you please adjust the base size or default size to 16? I think it should be the default for all text in our emails.

Can grab reference from: https://tailwindcss.com/docs/font-size

**Review by iamhectorsosa — APPROVED** [review]

**Review by iamhectorsosa — APPROVED** [review]

**Pull request merged**
