### PR TITLE
Pivot to standard MDX

### PR DESCRIPTION
**Pull request by ericvalcik**

### CODE REVIEW

**Comment by ericvalcik** [comment]
When working with the standart mdx implementation, the problem that arose was that we have to define the `shiki` related logic inside the `next.config.mjs` file. I managed to get it working in this PR and will continue to work on it, but this is a decision we have to think about.

So far, no other issues arose, so I will continue to work on this and we will see where we land. I think that working with the installation docs for each component can be a little bit more tricky so we will see.

**Comment by ericvalcik** [comment]
@ChcJohnie check this out. I feel like we have this working.

We need to clean the code a bit, but other than that I feel like this usage of the mdx files is better. What do you think?

**Comment by ericvalcik** [comment]
Regarding the frontmatter, `next/mdx` does not support it out of the box, they offer an alternative - exporting objects from mdx - more info [here](https://nextjs.org/docs/app/building-your-application/configuring/mdx#frontmatter). Or using `gray-matter`.

For me the big pros of using mdx are the following:
- that we no longer have to create scope of components + variables in the `page.tsx` file
- we can also drop the `dependencies` key in the `componentTypes` object - we control what we show in the `mdx` file itself
- related to the above point above - we can use async components in `mdx`, making it more usable and flexible.

However both cons mentioned by @ChcJohnie are fair and we have to take them into consideration.

Idea: We could possibly drop the `rehype-pretty-code` plugin all together and just use a component to render the code the way we like with our `@lib/shiki`, I think that should be possible

**Review by ChcJohnie — APPROVED** [review]
Nice chamges. 
As mentioned before I still see some cons with this solution but better flexibility of mdx writing is good enough reason to proceed. 
Next steps should include update of /blog routes to also use next/mdx and remove next-remote-mdx entirely and ideally add few more pages of docummentation. This should also clear up how big disadvantages are.
In meantime I would suggest not to entirely remove my #136 (or remove its branch) which will become deprecated by this but might be useful as backup.

**Pull request merged**
