### PR TITLE
Improve docs in `/components`

### PR DESCRIPTION
**Pull request by ericvalcik**
This PR is solving the #156 issue.

> I'd consider highlighting the fact that the components are intended to be used as copy-paste snippets (As this is not the usual approach and it might be confusing.)

we mention at the beginning that our components are intended to be used only as *copy and paste* components, but I made the mention a little more clear on the `/components` page to avoid confusion.

> I'd probably show an opinionated structure of the files that are necessary for the components to work (ideally somewhere close to the beginning of the docs). So that the users can have a better overview of what is necessary to set up as soon as possible.

added as a code block, but I think that should be sufficient. I was thinking about creating a component just for the filetree, but I think that should not be necessary.

> I'd consider simplifying the way we talk about the theme file. I'd probably only suggest the way we like the most sticking to a specific opinion and trying to prevent confusion. I don't really like the formulation of "place the file somewhere in the project". If we want to communicate the fact that it is not completely necessary to keep the structure, I'd rather mention it in a side note.

I agree with the confusion around _"place the file somewhere in the project"_, so I made that more opinionated,  but still left a note about the flexibility.

> Just a detail, but I don't quite like the fact that the theme alias reads "@mailingui/themes", while it exports just a single theme 😅

About the naming of the `@mailingui/themes`, if we decide to change that to `@mailingui/theme` we would also have to update all of the components (their code) and also the lib's internal code. I'm not sure if that's something we want, however it does not seem like a big task so I could include it in this PR, wdyt @iamhectorsosa ?

### CODE REVIEW

**Comment by ericvalcik** [comment]
Regarding the #155 issue, I got a couple of thoughts.

> First of all, I don't really think the CTA text on the home page is clear. At first, I was not sure how to get to the docs. "Get started" or "See the Docs" would be more straightforward. "Explore components" is actually a good CTA in my opinion, but it opens the installation docs page, which is very weird.

We are currently working on a fading collapsible in #152 that would hide the getting started docs by default, so I think the `Explore Components` is a good title for the CTA, what do you think? Also, I think that in the future we plan on adding templates that will have their own setup guide somewhere as well, so not all Documentation will be located in the `/components` route.

> A minor detail, there is a slight inconsistency between the CTA in the hero section and the CTA below the components "Explore components" vs "Explore Components".

Agreed 👍  I just changed the latter CTA title to "Explore All Components", so it makes more sense. Right now on the homepage we only show 3 components on mobile view and 8 on large view, which is the exact same number of components we have, so that can be confusing, but I'd leave it like this anyway. What do you guys think?

> It actually feels a bit weird to have the CTA under the actual links to the components. I'd actually expect the link to go to the very preview of the components it is under (or one that is quite similar to it) 😅

Same argument as for the two previous two comments. The `/components` route should and will be mainly an overview of all the components we have along with installation guides, so leaving the name as is makes sense.

---

As I'm thinking about this, we don't really have a docs page at all, we just have injected installation mdx files along with the components, so maybe we could create a new "Docs" page/group of pages with all the documentation (manual setup, CLI, how to install components, how to use preview mode, templates etc.).

There is a lot I wrote here, and most of it is just ideas, so please tell me what you guys think @alexxander @iamhectorsosa @ChcJohnie.

**Comment by ChcJohnie** [comment]
Actually in moments between other work I already started to work on /docs proposal which would greatly improve docs structure I believe.
I won't be able to finish that before my vacation and there are still quite many issues to resolve and structure discussion to have. But if someone can takeover I think it may be doable to have something usable during next week.
Expect draft PR with sum of current state and known issues by tomorrow morning.

**Comment by ericvalcik** [comment]
@ChcJohnie I think I should be able to pick up where you left off  with that, so please give me a heads up before your vacation.

**Comment by iamhectorsosa** [comment]
I agree that a better structure will make this project a lot easier to understand but now we kinda have to stick with what we have here. So, being how it is now, I would suggest that we agree on what label is best to represent this user flow and use the same label on both locations.

Changing the structure of how to docs is a task we *definitely* need to take, but we need to focus and prioritize shipping a V1 on this project and, if we have the bandwidth, creating more templates (bianco, viola, etc.).

@ericvalcik @ChcJohnie @alexxander

**Comment by iamhectorsosa** [comment]
@ChcJohnie exactly exactly what I thought as well 🙏🏼 theming and templates are still a big questions for now

**Comment by ericvalcik** [comment]
I agree with you guys, so the best for us would be to keep the documentation problem for later and focus on theming and templates now more. With that said, I think we could merge this PR now since it provides some small changes and improvements and then just focus on the higher priority stuff, wdyt guys?

Adding @iamhectorsosa and @alexxander as reviews so we can merge.

**Review by iamhectorsosa — APPROVED** [review]
Please go ahead and merge these changes and close the issues as addressed.

**Pull request merged**
